

services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - logger
      - account_db
    environment:
      DATABASE_URL: postgres://zenvis:467578@account_db/zenvis?sslmode=disable
      LOGGER_SERVICE_URL: logger:9000
    restart: on-failure

  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - logger
      - catalog_db
    environment:
      DATABASE_URL: http://catalog_db:9200
      LOGGER_SERVICE_URL: logger:9000
    restart: on-failure

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on:
      - logger
      - order_db
    environment:
      DATABASE_URL: postgres://zenvis:467578@order_db/zenvis?sslmode=disable
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
      LOGGER_SERVICE_URL: logger:9000
    restart: on-failure

  gateway:
    build:
      context: .
      dockerfile: ./gateway/app.dockerfile
    ports:
      - 8000:8080
    depends_on:
      - account
      - catalog
      - order
      - logger
    environment:
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
      ORDER_SERVICE_URL: order:8080
      LOGGER_SERVICE_URL: logger:9000
    restart: on-failure

  logger:
    volumes:
    - ./logger/logs/centralized.log:/root/centralized.log
    build:
      context: .
      dockerfile: ./logger/app.dockerfile

    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      LOGGER_SERVICE_URL: logger:9000
    


  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: zenvis
      POSTGRES_USER: zenvis
      POSTGRES_PASSWORD: 467578
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node

  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: zenvis
      POSTGRES_USER: zenvis
      POSTGRES_PASSWORD: 467578
    restart: unless-stopped