// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AccountInput struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Role     *string `json:"role,omitempty"`
}

type AuthResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	UserID       string `json:"userId"`
	Email        string `json:"email"`
	Role         string `json:"role"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LogoutInput struct {
	UserID string `json:"userId"`
}

type LogoutResponse struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

type Mutation struct {
}

type Order struct {
	ID         string            `json:"id"`
	CreatedAt  string            `json:"createdAt"`
	TotalPrice float64           `json:"totalPrice"`
	Products   []*OrderedProduct `json:"products"`
}

type OrderInput struct {
	AccountID string                 `json:"accountId"`
	Products  []*OrderedProductInput `json:"products,omitempty"`
}

type OrderStatusUpdate struct {
	OrderID   string `json:"orderId"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updatedAt"`
}

type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
	Stock       int     `json:"stock"`
}

type OrderedProductInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}

type Pagination struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int     `json:"stock"`
	Sold        int     `json:"sold"`
	OutOfStock  bool    `json:"outOfStock"`
	Score       float64 `json:"score"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int     `json:"stock"`
}

type Query struct {
}

type RefreshTokenInput struct {
	UserID string `json:"userId"`
}

type ResetPasswordInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ResetPasswordResponse struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

type Subscription struct {
}
